### ISSUE TITLE
Implement all the Map object's methods, so this is pretty much exactly equivalent

### ISSUE THREAD

**Issue by anko** [anko/array-keyed-map#1]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

It would be neato if this had all of that, and the readme could say "*It's literally exactly `Map`, but the keys are arrays*".

Tracking:

 - [x] `new Map()`
 - [x] `new Map([iterable])`
 - [x] `.size`
 - [x] `[@@toStringTag]`
 - [x] `[@@species]` (unnecessary; we're not prototype-deriving from `Map`)
 - [x] `.clear()`
 - [x] `.delete()`
 - [x] `.entries()`
 - [x] `.forEach()`
 - [x] `.get()`
 - [x] `.has()`
 - [x] `.keys()`
 - [x] `.set()`
 - [x] `.values()`
 - [x] `[@@iterator]()`

**Comment by michalczaplinski** [comment]
Are you open to a PR with a "proxified" version of the Map? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by anko** [comment]
@michalczaplinski How do you mean, in terms of API?

    let akmap = new require("array-keyed-map")()

    // Currently
    akmap.set(['a', 'b', 'c'], 42)

    // ① Do you mean this would be equivalent?
    akmap["a"]["b"]["c"] = 42

    // ② Or this?
    akmap[["path", "of", "keys"]] = 42 // Like this?

If you mean one of these alternatives, I considered them, but rejected them
because they have the same weakness as using plain Objects like this:  some
properties like `length` are special, and overwriting them causes problems.  I
figured having a `.set` and `.get` would guarantee a separate namespace.

Or did you mean something else?

**Comment by anko** [comment]
Added most things in https://github.com/anko/array-keyed-map/compare/b7982ec...a7aa1c6 (notably `clear`, and all the iterators) and published them in v1.2.0.  I think only extremely niche use-cases would now notice the difference at all, but I'll keep this issue open for reference.

**Comment by anko** [comment]
:sparkles: Done, published to npm in v1.3.0.
